### ISSUE TITLE
ews_soap_response.rb:31:in 'envelope' : undefined method '[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by Hareet** [WinRb/Viewpoint#166]
Doing a basic connection to Outlook Web Access, and trying to retrieve one mail message inside a specific folder.

require 'viewpoint'
include Viewpoint::EWS

endpoint = 'https://xxxxxx.xxxxxx.com/owa/'
user = 'xxxxx\xxxxx'
pass = 'xxxxxxx'

cli = Viewpoint::EWSClient.new endpoint, user, pass

retrieve = cli.get_folder_by_name('Event_Reports')
folders = cli.folders
puts retrieve
puts folders

retrieve.move_items(1, 'Event_Reports_Complete')

returns back the error in the subject. EWS_Soap_Response File is located in the Viewpoint gem

**Comment by whather** [comment]
I'm seeing this as well. Is there a workaround for this? 

This is the callstack:

```
/opt/outreach/shared/bundle/ruby/2.1.0/bundler/gems/Viewpoint-d67ae79eef4b/lib/ews/soap/ews_response.rb:31:in `envelope',
/opt/outreach/shared/bundle/ruby/2.1.0/bundler/gems/Viewpoint-d67ae79eef4b/lib/ews/soap/ews_response.rb:39:in `body',
/opt/outreach/shared/bundle/ruby/2.1.0/bundler/gems/Viewpoint-d67ae79eef4b/lib/ews/soap/ews_response.rb:43:in `response',
/opt/outreach/shared/bundle/ruby/2.1.0/bundler/gems/Viewpoint-d67ae79eef4b/lib/ews/soap/ews_response.rb:64:in `simplify!',
/opt/outreach/shared/bundle/ruby/2.1.0/bundler/gems/Viewpoint-d67ae79eef4b/lib/ews/soap/ews_response.rb:27:in `initialize',
/opt/outreach/shared/bundle/ruby/2.1.0/bundler/gems/Viewpoint-d67ae79eef4b/lib/ews/soap/parsers/ews_parser.rb:32:in `new',
/opt/outreach/shared/bundle/ruby/2.1.0/bundler/gems/Viewpoint-d67ae79eef4b/lib/ews/soap/parsers/ews_parser.rb:32:in `parse',
/opt/outreach/shared/bundle/ruby/2.1.0/bundler/gems/Viewpoint-d67ae79eef4b/lib/ews/soap/exchange_web_service.rb:221:in `parse_soap_response',
/opt/outreach/shared/bundle/ruby/2.1.0/bundler/gems/Viewpoint-d67ae79eef4b/lib/ews/connection.rb:74:in `dispatch',
/opt/outreach/shared/bundle/ruby/2.1.0/bundler/gems/Viewpoint-d67ae79eef4b/lib/ews/soap/exchange_web_service.rb:212:in `do_soap_request',
/opt/outreach/shared/bundle/ruby/2.1.0/bundler/gems/Viewpoint-d67ae79eef4b/lib/ews/soap/exchange_data_services.rb:88:in `get_item',
/opt/outreach/shared/bundle/ruby/2.1.0/bundler/gems/Viewpoint-d67ae79eef4b/lib/ews/item_accessors.rb:61:in `get_items'
```

**Comment by gshutler** [comment]
@Hareet @whather is this still an active issue for you? If so can you see if #253 resolves it for you?
