### ISSUE TITLE
uninitialized constant Viewpoint::EWS::Types::PostItem

### ISSUE THREAD

**Issue by jwg2s** [WinRb/Viewpoint#206]
Receiving this error while fetching messages -- is this expected?  Should we rescue from this somehow?

```
/app/vendor/bundle/ruby/2.2.0/bundler/gems/Viewpoint-a743e2ef965f/lib/ews/types.rb:111:in `const_get'
/app/vendor/bundle/ruby/2.2.0/bundler/gems/Viewpoint-a743e2ef965f/lib/ews/types.rb:111:in `class_by_name'
/app/vendor/bundle/ruby/2.2.0/bundler/gems/Viewpoint-a743e2ef965f/lib/ews/types/generic_folder.rb:381:in `block in items_parser'
/app/vendor/bundle/ruby/2.2.0/bundler/gems/Viewpoint-a743e2ef965f/lib/ews/types/generic_folder.rb:379:in `each'
/app/vendor/bundle/ruby/2.2.0/bundler/gems/Viewpoint-a743e2ef965f/lib/ews/types/generic_folder.rb:379:in `items_parser'
/app/vendor/bundle/ruby/2.2.0/bundler/gems/Viewpoint-a743e2ef965f/lib/ews/types/generic_folder.rb:80:in `items'
/app/vendor/bundle/ruby/2.2.0/bundler/gems/Viewpoint-a743e2ef965f/lib/ews/types/generic_folder.rb:107:in `items_between'
```

**Comment by zenchild** [comment]
Just pushed a fix up to master. I just haven't come across that type before. At the moment it's just a generic type so if you need any additional functionality you'll have to add it.
