### ISSUE TITLE
When forwarding email

### ISSUE THREAD

**Issue by StephanMeijer** [WinRb/Viewpoint#233]
```
Viewpoint::EWS::Errors::SoapResponseError: SOAP Error: Message: The request failed schema validation: The element 'ForwardItem' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types' has invalid child element 'Importance' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'. List of possible elements expected: 'Subject, Body, ToRecipients, CcRecipients, BccRecipients, IsReadReceiptRequested, IsDeliveryReceiptRequested, From, ReferenceItemId, NewBodyContent' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'.  Code: a:ErrorSchemaValidation
        from /var/lib/gems/2.1.0/gems/viewpoint-1.0.0/lib/ews/connection.rb:107:in `check_response'
        from /var/lib/gems/2.1.0/gems/viewpoint-1.0.0/lib/ews/connection.rb:89:in `post'
        from /var/lib/gems/2.1.0/gems/viewpoint-1.0.0/lib/ews/connection.rb:67:in `dispatch'
        from /var/lib/gems/2.1.0/gems/viewpoint-1.0.0/lib/ews/soap/exchange_web_service.rb:212:in `do_soap_request'
        from /var/lib/gems/2.1.0/gems/viewpoint-1.0.0/lib/ews/soap/exchange_data_services.rb:150:in `create_item'
        from /var/lib/gems/2.1.0/gems/viewpoint-1.0.0/lib/ews/types/item.rb:415:in `dispatch_create_item!'
        from /var/lib/gems/2.1.0/gems/viewpoint-1.0.0/lib/ews/types/item.rb:237:in `forward'
        from (irb):77
        from /usr/bin/irb:11:in `<main>'
```

```
item = cli.get_folder_by_name('Postvak IN').items[0]

item.forward do |i|
    i.new_body_content = "Add this to the top"
    i.to_recipients << 'test@test.com'
end
```

**Comment by StephanMeijer** [comment]
Same issue as #168. Closed
