### ISSUE TITLE
Add additional documentation on subscribing to folder on md

### ISSUE THREAD

**Issue by SternAndrew** [WinRb/Viewpoint#240]
Please add a sample like this to show how to get all emails from the inbox and to subscribe for future updates to that folder.  Note that this code generally works but there seems to be a bug in the get_events call that after running for a while it calls a method on a nil.  Here is the stack trace:

/home/user/.gem/ruby/gems/viewpoint-1.0.0/lib/ews/soap/responses/get_events_response_message.rb:35:in `new_watermark': undefined method`last' for nil:NilClass (NoMethodError)
        from /home/user/.gem/ruby/gems/viewpoint-1.0.0/lib/ews/types/generic_folder.rb:292:in `get_events'

it looks like notification should be checked for nil before calling last.  Adding code change below my sample.  Also added a pull request for this change.

```
require 'rubygems'
require 'stringio'
require 'io/console'
#require 'byebug'

def silent_warnings
  old_stderr = $stderr
  $stderr = StringIO.new
  yield
ensure
  $stderr = old_stderr
end

silent_warnings do
  require 'viewpoint' # Library for MS Outlook
  #require 'viewpoint/logging/config' # For Debugging

  include Viewpoint::EWS
end

def processItem(item)
  subject = item.subject.gsub 'Warning', "\x1b[38;2;234;236;35mWarning\x1b[0;00m"
  subject = subject.gsub 'WARNING', "\x1b[38;2;234;236;35mWARNING\x1b[0;00m"
  subject = subject.gsub 'CRITICAL', "\x1b[38;2;234;236;35mCRITICAL\x1b[0;00m"
  from = item.from.name

  puts "  #{item.date_time_sent.to_time.localtime.strftime("%Y-%m-%d %H:%M:%S")}: #{subject} from #{from}"

  # If you need the body of the message and it is in HTML format you can use Nokogiri to translate it to a text format to search.
  # puts Nokogiri::HTML(item.body).text.gsub "<!--.*-->", ""
end

print "Enter Password: "
password = STDIN.noecho(&:gets).chomp

endpoint = 'https://OUTLOOKSERVER.com/EWS/Exchange.asmx' # E.g. https://OUTLOOKSERVER_URL/ews/exchange.asmx
username = 'domain\username'
# Can also use the following for username
#username = 'user.name@company.com'

cli = Viewpoint::EWSClient.new endpoint, username, password, http_opts: {ssl_verify_mode: 0}
# Attempt to grab authentication from Domain Login
# cli.ews.connection.authenticate

folders = cli.folders
inbox = cli.get_folder_by_name 'Inbox'
items = inbox.items

puts
puts "There are #{items.count} messages"
puts "Subjects: "

items.reverse_each do |item|
  processItem(item)
end

inbox.subscribe(evtypes = [:new_mail], watermark = nil, timeout = 600)
while true
  sleep(30) # Sleep for 30 seconds
  # Make sure we are subscribed before getting the events since we can lose our subscription.
  inbox.subscribe(evtypes = [:new_mail], watermark = nil, timeout = 600) unless inbox.subscribed?
  inboxEvents = inbox.get_events
  begin
    if inboxEvents
      items_returned_by_event = inboxEvents.map{|i| i.ews_item[:item_id][:attribs][:id] if i.ews_item[:item_id]}.compact
      items_returned_by_event.each do |item_id|
        item = inbox.get_item(item_id)
          processItem(item)
      end
    end
  rescue => e
    # print "Hit exception while processing items:", e, "\n"
    # print "exception:\n", e.backtrace, "\n";
  end
end

```

Original code

```
    def new_watermark
      ev = notification.last
      if ev
        type = ev.keys.first
        ev[type][:elems][0][:watermark][:text]
      else
        nil
      end
    end
```

Patched code

```
    def new_watermark
      if notification
        ev = notification.last
        if ev
          type = ev.keys.first
          ev[type][:elems][0][:watermark][:text]
        else
          nil
        end
      else
        nil
      end
    end
```

**Comment by pcai** [comment]
Closing this out — the reported crash is guarded against on main and folder subscription is documented. Thanks for reporting!
