### ISSUE TITLE
Exception in code

### ISSUE THREAD

**Issue by SternAndrew** [WinRb/Viewpoint#242]
I would fix this but not yet sure where the check should be to prevent this issue.  Here is the stack trace of the exception:

```

/home/astern/.gem/ruby/gems/viewpoint-1.0.0/lib/ews/soap/ews_response.rb:31:in `envelope': undefined method `[]' for nil:NilClass (NoMethodError)
        from /home/astern/.gem/ruby/gems/viewpoint-1.0.0/lib/ews/soap/ews_response.rb:39:in `body'
        from /home/astern/.gem/ruby/gems/viewpoint-1.0.0/lib/ews/soap/ews_response.rb:43:in `response'
        from /home/astern/.gem/ruby/gems/viewpoint-1.0.0/lib/ews/soap/ews_response.rb:64:in `simplify!'
        from /home/astern/.gem/ruby/gems/viewpoint-1.0.0/lib/ews/soap/ews_response.rb:27:in `initialize'
        from /home/astern/.gem/ruby/gems/viewpoint-1.0.0/lib/ews/soap/parsers/ews_parser.rb:32:in `new'
        from /home/astern/.gem/ruby/gems/viewpoint-1.0.0/lib/ews/soap/parsers/ews_parser.rb:32:in `parse'
        from /home/astern/.gem/ruby/gems/viewpoint-1.0.0/lib/ews/soap/exchange_web_service.rb:221:in `parse_soap_response'
        from /home/astern/.gem/ruby/gems/viewpoint-1.0.0/lib/ews/connection.rb:74:in `dispatch'
        from /home/astern/.gem/ruby/gems/viewpoint-1.0.0/lib/ews/soap/exchange_web_service.rb:212:in `do_soap_request'
        from /home/astern/.gem/ruby/gems/viewpoint-1.0.0/lib/ews/soap/exchange_data_services.rb:87:in `get_item'
        from /home/astern/.gem/ruby/gems/viewpoint-1.0.0/lib/ews/item_accessors.rb:33:in `get_item'
        from /cygdrive/c/Users/astern/Desktop/outlook.rb:60:in `block in <main>'
        from /cygdrive/c/Users/astern/Desktop/outlook.rb:59:in `each'
        from /cygdrive/c/Users/astern/Desktop/outlook.rb:59:in `<main>'

```

**Comment by jcarbo** [comment]
I'm seeing a similar issue. Here's the stack trace:

```
NoMethodError: undefined method `each' for nil:NilClass
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/Viewpoint-5475b290d558/lib/ews/soap/ews_response.rb:65:in `simplify!'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/Viewpoint-5475b290d558/lib/ews/soap/ews_response.rb:27:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/Viewpoint-5475b290d558/lib/ews/soap/parsers/ews_parser.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/Viewpoint-5475b290d558/lib/ews/soap/parsers/ews_parser.rb:32:in `parse'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/Viewpoint-5475b290d558/lib/ews/soap/exchange_web_service.rb:221:in `parse_soap_response'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/Viewpoint-5475b290d558/lib/ews/connection.rb:78:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/Viewpoint-5475b290d558/lib/ews/soap/exchange_web_service.rb:212:in `do_soap_request'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/Viewpoint-5475b290d558/lib/ews/soap/exchange_data_services.rb:52:in `find_item'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/Viewpoint-5475b290d558/lib/ews/types/generic_folder.rb:79:in `items'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/Viewpoint-5475b290d558/lib/ews/types/generic_folder.rb:107:in `items_between'
```

The server we're looking at is Exchange version 2010.

**Comment by mojobiri** [comment]
+1 @jcarbo
