### ISSUE TITLE
uninitialized constant Viewpoint::EWS::Connection::Logging

### ISSUE THREAD

**Issue by cgoodnight** [WinRb/Viewpoint#275]
Running on windows, when I run the script from command line viewpoint works fine and I can check emails.  But when I run under task scheduler, I get the failure in viewpoint
<NameError: uninitialized constant Viewpoint::EWS::Connection::Logging
Did you mean?  Logger>
 C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/viewpoint-1.1.0/lib/ews/connection.rb:36:in `initialize'
 C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/viewpoint-1.1.0/lib/ews/ews_client.rb:49:in `new'
 C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/viewpoint-1.1.0/lib/ews/ews_client.rb:49:in `initialize'

All other gems run fine, I have reset permissions.  Checked that logging is being loaded while under the task scheduler account.  It is.

**Comment by pcai** [comment]
Fixed by #302 — the `logging` gem is replaced with stdlib `logger`.
